spring.application.name=banking
spring.datasource.url=jdbc:postgresql://localhost:5432/Mastra
spring.datasource.username=ArloDanteHananvyasa
spring.datasource.password=Hananvyasa21
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=hJfn51iEAl3Wra1u1j8gkrQ7kDU5OCyV
jwt.expiration=3600000