spring.application.name=banking
spring.datasource.url=jdbc:postgresql://localhost:5432/Mastra
spring.datasource.username=Arlo
spring.datasource.password=Hananvyasa21
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true